server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: interactive-backend
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin}

astra:
  token: ${ASTRA_TOKEN}
  api-endpoint: ${ASTRA_API_ENDPOINT}
  database-id: ${ASTRA_DATABASE_ID}
  keyspace: ${ASTRA_KEYSPACE:default_keyspace}

logging:
  level:
    org.springframework.web: INFO
    com.example.presentation: DEBUG 